name: build

# Run manually and each time anything is pushed or a PR is made
# Will only create a release for tagged commits
on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    name: Lint, build, and release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
            components: clippy

      - name: Lint and compile
        shell: bash
        run: |-
          cargo clippy --no-deps -- --deny warnings
          cargo build --release

      # Create a release and upload a build if this is a tag starting with "v"
      - name: Get version
        id: version
        if: "startsWith(github.ref, 'refs/tags/v')"
        shell: bash
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Create release
        id: create_release
        if: "startsWith(github.ref, 'refs/tags/v')"
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.VERSION }}
          release_name: ngfe-traymon ${{ steps.version.outputs.VERSION }}
          draft: false
          prerelease: false

      - name: Add build to release
        uses: actions/upload-release-asset@v1
        if: "startsWith(github.ref, 'refs/tags/v')"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/release/ngfe-traymon.exe
          asset_name: ngfe-traymon.exe
          asset_content_type: application/octet-stream